import type { ReferralPacket, Patient, CNNOutputTool, RecentSoundRecord } from '../../types';

class ReferralService {
  buildReferralPacket(
    patient: Patient,
    latestResult: CNNOutputTool,
    recentSessions: RecentSoundRecord[],
    symptoms: string[],
    aiSummary: string
  ): ReferralPacket {
    return {
      patientSummary: {
        name: patient.name,
        age: patient.age,
        sex: patient.sex,
        comorbidities: patient.comorbidities,
        medications: patient.medications,
      },
      latestCnnResult: latestResult,
      recentSessions,
      symptomTimeline: symptoms,
      aiConversationSummary: aiSummary,
      urgencyLevel: latestResult.pneumoniaRiskBucket,
    };
  }

  async submitToESanjeevani(packet: ReferralPacket): Promise<{ success: boolean; referralId: string }> {
    await new Promise((r) => setTimeout(r, 1500));

    return {
      success: true,
      referralId: `ESANJ-${Date.now()}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`,
    };
  }

  generatePdfSummary(packet: ReferralPacket): string {
    const lines: string[] = [
      '═══════════════════════════════════════',
      '        PneumoScan Clinical Summary    ',
      '═══════════════════════════════════════',
      '',
      `Patient: ${packet.patientSummary.name}`,
      `Age: ${packet.patientSummary.age} | Sex: ${packet.patientSummary.sex}`,
      `Comorbidities: ${packet.patientSummary.comorbidities.join(', ') || 'None'}`,
      `Medications: ${packet.patientSummary.medications.join(', ') || 'None'}`,
      '',
      '--- Latest Screening Result ---',
      `Date: ${packet.latestCnnResult.capturedAt}`,
      `Signal Source: ${packet.latestCnnResult.signalSource}`,
      `Pneumonia Risk: ${packet.latestCnnResult.pneumoniaRiskBucket.toUpperCase()}`,
      `Confidence: ${(packet.latestCnnResult.confidence * 100).toFixed(1)}%`,
      `Trend: ${packet.latestCnnResult.trend}`,
      '',
      '--- Urgency ---',
      `Level: ${packet.urgencyLevel.toUpperCase()}`,
      '',
      '--- AI Assessment Summary ---',
      packet.aiConversationSummary,
      '',
      '═══════════════════════════════════════',
      'Generated by PneumoScan | Not a diagnosis',
      '═══════════════════════════════════════',
    ];
    return lines.join('\n');
  }
}

export const referralService = new ReferralService();
